id: PADCF4F6D
initial_creation_type: input
source_metadata:
  Title: Pratimoksa sutra of Mahasanghikas
  Editor: W.Pachow and Ramakanta Mishra
  Publisher: Ganganatha Jha Research Institute
  Place of Publication: Allahabad, India
  Year: '1956'
  Mahāsāṃghikānāṃ prātimokṣasūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:15:56.104216'
last_modified_at: '2022-03-08T16:15:56.104223'
